name: 'Get & cache dependencies'
description: 'Get & cache dependencies'
inputs:
  caching:
    description: 'Enable caching'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether cache was used'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash