name: Events demo 1
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue details
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "deploying..."
