name: Output issue details
on: issues
jobs:
  output_issue_details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output issue details
        run: echo "${{ toJson(github.event) }}"