name: Reusable workflow deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the deployable artifact
        required: true
        type: string
    outputs:
      result:
        description: result of the deploy
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Deploy info
        run: echo "deploying..."
      - name: Set result value
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT